#!/usr/bin/env bash
# Regenerates the hash-pinned requirement files that build-app.sh installs with `pip install --require-hashes`:
#   scripts/python-requirements.txt        everything packages/secret-gate needs at run time, one version each
#   scripts/python-build-requirements.txt  setuptools, which builds the secret-gate wheel (no build isolation)
# Versions come from scripts/python-constraints.txt (the tested set of packages/secret-gate/.venv). pip on the
# bundled CPython (runtime-pins.sh) resolves secret-gate's pyproject requirements against them, wheels only, and
# its installation report gives the SHA-256 the index publishes for each file it picks. Every file is then
# downloaded and checked against the written hashes, so the output is known to install.
#
#   scripts/lock-python.sh    after changing python-constraints.txt, secret-gate's dependencies or the Python pin;
#                             review the diff and commit both files
set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
CACHE="$HERE/.build-cache"
# shellcheck source=runtime-pins.sh
source "$HERE/scripts/runtime-pins.sh"

WORK="$(mktemp -d "${TMPDIR:-/tmp}/agentswitch-lock.XXXXXX")"
trap 'rm -rf "$WORK"' EXIT
PY="$WORK/python/bin/python$PY_MINOR"
PYPROJECT="$REPO/packages/secret-gate/pyproject.toml"
CONSTRAINTS="$HERE/scripts/python-constraints.txt"

fetch "$PYTHON_URL" "$PYTHON_TARBALL" "$PYTHON_SHA256"
extract "$PYTHON_TARBALL" "$WORK/python"
[ -x "$PY" ] || die "unexpected python-build-standalone layout"

pip() { PIP_CACHE_DIR="$CACHE/pip" "$PY" -m pip --disable-pip-version-check --no-input "$@"; }

# requirements <dotted key of pyproject.toml>: one requirement per line
requirements() {
  "$PY" -I -c 'import sys, tomllib
table = tomllib.load(open(sys.argv[1], "rb"))
for key in sys.argv[2].split("."):
    table = table[key]
print("\n".join(table))' "$PYPROJECT" "$1"
}

# lock <out> <pyproject key> [pip args...]: resolve, write `name==version --hash` lines, prove they install.
lock() {
  local out="$1" key="$2"; shift 2
  requirements "$key" > "$WORK/in.txt"
  rm -f "$WORK/report.json"
  pip install --quiet --dry-run --ignore-installed --only-binary=:all: --report "$WORK/report.json" -r "$WORK/in.txt" "$@"
  "$PY" -I - "$WORK/report.json" "$key" "$CONSTRAINTS" > "$WORK/out.txt" <<'PY'
import json, re, sys

report_path, key, constraints_path = sys.argv[1:4]
norm = lambda name: re.sub(r"[-_.]+", "-", name).lower()
pinned = {norm(line.split("==")[0]) for line in open(constraints_path) if "==" in line and not line.startswith("#")}
print("# Generated by scripts/lock-python.sh; do not edit by hand. Rerun it after changing")
print(f"# scripts/python-constraints.txt or `{key}` in packages/secret-gate/pyproject.toml.")
if key == "project.dependencies":
    print("# build-app.sh installs this with `pip install --require-hashes --only-binary=:all:` into the bundled")
    print("# CPython (scripts/runtime-pins.sh, darwin arm64): one version per package, the SHA-256 of the file pip picks.")
else:
    print("# build-app.sh installs this with `pip install --require-hashes --only-binary=:all:` into a throw-away")
    print("# directory that builds the secret-gate wheel; it never enters the bundle. SHA-256 of the file pip picks.")
for item in sorted(json.load(open(report_path))["install"], key=lambda i: norm(i["metadata"]["name"])):
    meta, info = item["metadata"], item["download_info"]
    sha = info.get("archive_info", {}).get("hashes", {}).get("sha256")
    if not sha:
        sys.exit(f"no sha256 from the index for {meta['name']} ({info.get('url')})")
    if key == "project.dependencies" and norm(meta["name"]) not in pinned:
        print(f"warning: {meta['name']} {meta['version']} is not pinned in python-constraints.txt", file=sys.stderr)
    print(f"{norm(meta['name'])}=={meta['version']} \\\n    --hash=sha256:{sha}")
PY
  rm -rf "$WORK/check"
  pip download --quiet --require-hashes --only-binary=:all: --no-deps -d "$WORK/check" -r "$WORK/out.txt"
  mv "$WORK/out.txt" "$out"
  echo "wrote $out ($(grep -c -- '--hash=' "$out") packages)"
}

log "resolving secret-gate's dependencies against python-constraints.txt"
lock "$HERE/scripts/python-requirements.txt" project.dependencies -c "$CONSTRAINTS"
log "resolving secret-gate's build backend"
lock "$HERE/scripts/python-build-requirements.txt" build-system.requires
