"""Per-harness config snippets with real paths filled in, for `secret-gate bootstrap`.

The shapes are those of `config/*.snippet*` (a test keeps generator and shipped files identical when both use
the `/Users/YOU` placeholders). Built in code rather than by text substitution so the output is always valid
JSON / TOML and does not depend on where the repo lives.

Each result says what applying it would change. Proxy settings are scoped the same way the snippets and the
e2e findings require: Claude Code gets them in its settings `env` (its own API hosts stay in NO_PROXY), Codex
only in `shell_environment_policy.set` (its own websocket must never see them), OpenCode in the environment of
the shell that launches it. CA trust always travels as environment variables of that harness, never through
the keychain.
"""

from __future__ import annotations

import json
import shlex
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from .constants import CA_CERT_FILE
from .errors import ValidationError

HARNESS_CLAUDE = "claude-code"
HARNESS_CODEX = "codex"
HARNESS_OPENCODE = "opencode"
HARNESSES = (HARNESS_CLAUDE, HARNESS_CODEX, HARNESS_OPENCODE)

# Kept direct (not through the gate): each harness's own model API, as in the shipped snippets.
CLAUDE_NO_PROXY = "api.anthropic.com,.anthropic.com,claude.ai,.claude.ai,api.openai.com,api.deepseek.com,localhost"
CODEX_NO_PROXY = "api.openai.com,api.anthropic.com,api.deepseek.com,localhost"
# OpenCode's CLI talks to its own server over 127.0.0.1 and honours the proxy there (README, OpenCode specifics).
OPENCODE_NO_PROXY = "127.0.0.1," + CLAUDE_NO_PROXY
CA_ENV_VARS = ("SSL_CERT_FILE", "REQUESTS_CA_BUNDLE", "NODE_EXTRA_CA_CERTS")
OPENCODE_SCHEMA = "https://opencode.ai/config.json"


@dataclass(frozen=True)
class HarnessConfig:
    harness: str
    snippet: str                # the file content: stdout, or --write PATH
    apply: tuple[str, ...]      # where it goes; nothing here is done automatically
    scope: tuple[str, ...]      # what applying it changes


@dataclass(frozen=True)
class GateContext:
    home: Path                  # gate home (absolute)
    port: int
    command: tuple[str, ...]    # how to run this secret-gate installation
    user_home: Path

    @property
    def proxy_url(self) -> str:
        return f"http://127.0.0.1:{self.port}"

    @property
    def ca_path(self) -> str:
        return str(self.home / CA_CERT_FILE)


def proxy_env(ctx: GateContext, no_proxy: str) -> dict[str, str]:
    """Both cases on purpose: curl honours lowercase http_proxy only (httpoxy mitigation)."""
    url = ctx.proxy_url
    return {
        "HTTPS_PROXY": url, "https_proxy": url, "HTTP_PROXY": url, "http_proxy": url,
        "NO_PROXY": no_proxy, "no_proxy": no_proxy,
        **{name: ctx.ca_path for name in CA_ENV_VARS},
    }


def _tilde(path: Path, user_home: Path) -> str | None:
    try:
        return "~/" + path.relative_to(user_home).as_posix()
    except ValueError:
        return None


def claude_code(ctx: GateContext) -> HarnessConfig:
    tilde = _tilde(ctx.home, ctx.user_home)
    # Claude Code permission paths: `~/x` is the user's home, `//x` an absolute path.
    read_rule = f"Read({tilde}/**)" if tilde else f"Read(/{ctx.home}/**)"
    cat_rule = f"Bash(cat {tilde or ctx.home}/*)"
    settings = {
        "env": {"SECRET_GATE_HOME": str(ctx.home), **proxy_env(ctx, CLAUDE_NO_PROXY)},
        "permissions": {"deny": [read_rule, cat_rule, "Bash(secret-gate keygen*)"]},
    }
    mcp = shlex.join(["claude", "mcp", "add", "--scope", "local", "-e", f"SECRET_GATE_HOME={ctx.home}",
                      "secret-gate", "--", *ctx.command, "mcp"])
    return HarnessConfig(
        harness=HARNESS_CLAUDE,
        snippet=json.dumps(settings, indent=2) + "\n",
        apply=(
            "one session: claude --settings <file>; every session: merge `env` and `permissions` into "
            "~/.claude/settings.json yourself",
            f"MCP tools (optional, run it yourself; local scope = this project only): {mcp}",
        ),
        scope=(
            "every process of that Claude Code session (Bash tool, MCP servers) sends HTTP(S) through the gate; "
            "its own API hosts stay direct via NO_PROXY",
            "the deny rules keep the session's Read/Bash tools away from the gate home; they are guidance "
            "for the harness, not a security boundary",
        ),
    )


def _toml_str(value: str) -> str:
    return json.dumps(value)  # a JSON string literal is a valid TOML basic string


def _toml_inline(table: dict[str, str]) -> str:
    return "{ " + ", ".join(f"{k} = {_toml_str(v)}" for k, v in table.items()) + " }"


def codex(ctx: GateContext) -> HarnessConfig:
    command, *args = ctx.command
    text = "\n".join((
        "# Generated by `secret-gate bootstrap codex`. Merge these sections into $CODEX_HOME/config.toml",
        "# (default ~/.codex/config.toml) yourself, or use them as the config.toml of a dedicated CODEX_HOME.",
        "#",
        "# Proxy variables go ONLY here (shell tool env). Do not export them in the shell that launches",
        "# codex: Codex's own websocket to chatgpt.com honours them and would be captured by the gate.",
        "",
        "[shell_environment_policy]",
        'inherit = "all"',
        "# Both cases on purpose: curl honours lowercase http_proxy only (httpoxy mitigation).",
        f"set = {_toml_inline(proxy_env(ctx, CODEX_NO_PROXY))}",
        "",
        "# Codex sandbox blocks all sockets by default, including localhost: the proxy needs this.",
        "[sandbox_workspace_write]",
        "network_access = true",
        "",
        "[mcp_servers.secret-gate]",
        f"command = {_toml_str(command)}",
        "args = [" + ", ".join(_toml_str(a) for a in (*args, "mcp")) + "]",
        "",
        "[mcp_servers.secret-gate.env]",
        f"SECRET_GATE_HOME = {_toml_str(str(ctx.home))}",
        "",
    ))
    return HarnessConfig(
        harness=HARNESS_CODEX,
        snippet=text,
        apply=("merge into $CODEX_HOME/config.toml yourself (or give Codex a dedicated CODEX_HOME)",),
        scope=(
            "proxy and CA variables reach the shell tool only (shell_environment_policy.set); Codex's own "
            "traffic stays direct",
            "network_access = true lets every workspace-write sandboxed command open sockets, not only "
            "connections to the gate",
            "adds an MCP server entry `secret-gate` running this installation",
        ),
    )


def opencode_launch_env(ctx: GateContext) -> tuple[str, ...]:
    env = {"SECRET_GATE_HOME": str(ctx.home), **proxy_env(ctx, OPENCODE_NO_PROXY)}
    return tuple(f"export {k}={shlex.quote(v)}" for k, v in env.items())


def opencode(ctx: GateContext) -> HarnessConfig:
    home = str(ctx.home)
    config = {
        "$schema": OPENCODE_SCHEMA,
        "instructions": ["AGENTS.md"],
        "mcp": {"secret-gate": {"type": "local", "command": [*ctx.command, "mcp"], "enabled": True,
                                "environment": {"SECRET_GATE_HOME": home}}},
        "permission": {
            "read": {"*": "allow", f"{home}/*": "deny"},
            "bash": {"*": "allow", "secret-gate keygen*": "deny", f"cat {home}/*": "deny"},
        },
    }
    return HarnessConfig(
        harness=HARNESS_OPENCODE,
        snippet=json.dumps(config, indent=2) + "\n",
        apply=(
            "save as the project's ./opencode.json (or point OPENCODE_CONFIG at the file)",
            "the proxy is not in that file: run these in the shell that launches opencode, then use "
            "`opencode run --standalone` (the background service keeps the env it was started with):",
            *(f"  {line}" for line in opencode_launch_env(ctx)),
        ),
        scope=(
            "the exports apply to that shell and everything it starts; OpenCode's own model calls ignore "
            "the proxy, 127.0.0.1 stays direct for its CLI-to-server loopback",
            "adds an MCP server entry `secret-gate` running this installation",
        ),
    )


BUILDERS: dict[str, Callable[[GateContext], HarnessConfig]] = {
    HARNESS_CLAUDE: claude_code,
    HARNESS_CODEX: codex,
    HARNESS_OPENCODE: opencode,
}


def harness_config(harness: str, ctx: GateContext) -> HarnessConfig:
    builder = BUILDERS.get(harness)
    if builder is None:
        raise ValidationError(f"unknown harness {harness!r}; one of {', '.join(HARNESSES)}")
    return builder(ctx)
